<?php

/**
 * Implements hook_cron().
 */
function premios_cron()
{
    \Drupal::service('premios.cron')->run();
}

/**
 * Implements hook_mail().
 *
 * @see \Drupal\premios\Mail\MailHandler
 */
function premios_mail(string $key, array &$message, array $params): void
{
    /** @var \Drupal\Core\Render\RendererInterface $renderer */
    $renderer = \Drupal::service('renderer');
    if (isset($params['headers'])) {
        $message['headers'] = array_merge($message['headers'], $params['headers']);
    }
    if (!empty($params['from'])) {
        $message['from'] = $params['from'];
    }
    $message['subject'] = $params['subject'];
    $message['body'][] = $renderer->renderPlain($params['body']);
}
