<?php

use Drupal\sorteos\Entity\Sorteo;
use Drupal\image\Entity\ImageStyle;

function premios_theme()
{
    return [
        'premios_email' => [
            'variables' => [
                'commerce_order' => [],
                'order_item' => [],
                'prize' => '',
                'decimo' => '',
                'numero' => ''
            ],
        ]
    ];
}

function premios_preprocess_premios_email(&$variables)
{
    $order_item = $variables['order_item'];
    $qu = $order_item->get('quantity')->getValue();
    $tp = $order_item->get('total_price')->getValue();
    $variables['cantidad'] = $qu[0]['value'];
    $variables['precio_total'] = $tp[0]['number'];
    $product_variation = $order_item->getPurchasedEntity();
    $product = $product_variation->getProduct();
    if ($product->bundle() == 'decimo_loteria') {
        $numero = $product->get('field_numero_decimo')->get(0);

        $item = $product->get('field_sorteo_3')->get(0);

        $value = FALSE;
        if (!empty($item)) {
            $value = $item->getValue();
        }
        $sorteoid = $value['target_id'];
        $sorteo = Sorteo::load($sorteoid);

        $uri = $sorteo->field_decimo_imagen->entity->getFileUri();

        $variables['decimo'] = file_url_transform_relative(file_create_url($uri));

        $numeroarr = $numero->getValue();
        $variables['numero'] = $numeroarr['value'];
    }
}

/**
 * Implements hook_mail().
 *
 * @see \Drupal\premios\Mail\MailHandler
 */
function premios_mail(string $key, array &$message, array $params): void
{
    switch ($key) {
        case 'premios_mail':
            /** @var \Drupal\Core\Render\RendererInterface $renderer */
            $renderer = \Drupal::service('renderer');
            if (isset($params['headers'])) {
                $message['headers'] = array_merge($message['headers'], $params['headers']);
            }
            if (!empty($params['from'])) {
                $message['from'] = $params['from'];
            }
            $message['subject'] = $params['subject'];
            //$message['body'][] = $renderer->renderPlain($params['body']);

            $theme_body = array(
                '#theme' => 'premios_email',
                '#commerce_order' => $params['commerce_order'],
                '#order_item' => $params['commerce_order_item'],
                '#prize' => $params['prize']
            );

            $message['body'][] = \Drupal::service('renderer')->render($theme_body);
            break;
    }
}
