<?php

use Drupal\sorteos\SorteosConnection;
use Drupal\Core\Render\Element;

function sorteos_cron()
{
  $soc = new SorteosConnection();
  //$soc->checkSorteos();
  // Coge los sorteos de la semana de Loteria nacional los lunes
  if (date("N") == "1") {
    $soc->checkSorteosLNAC();
  }
  //$values = drush_invoke_process("@site", "sir", array("all"), array("verbose"));
  //drupal_set_message('Ejecutando sorteos cron');
  //\Drupal::logger('sorteos')->error('Ejecutando sorteos cron');
}

/**
 * Implements hook_theme().
 */
function sorteos_theme()
{
  return [
    'sorteos' => [
      'render element' => 'children',
    ],
    'sorteo' => [
      'path' => '/sorteos',
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_commerce_product().
 */
function sorteos_theme_suggestions_sorteo_alter(array &$suggestions, array $variables, $hook)
{
  $original = $variables['theme_hook_original'];
  $entity = $variables['elements']['#sorteo'];
  $suggestions[] = $original . '__' . $entity->bundle();
  return $suggestions;
}

/**
 * Prepares variables for sorteo templates.
 *
 * Default template: commerce-product.html.twig.
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing rendered fields.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_sorteo(array &$variables)
{
  /** @var Drupal\sorteos\Entity\SorteoInterface $product */
  $sorteo = $variables['elements']['#sorteo'];

  $variables['sorteo_entity'] = $sorteo;
  $variables['sorteo'] = [];
  foreach (Element::children($variables['elements']) as $key) {

    $variables['sorteo'][$key] = $variables['elements'][$key];
  }
  if ($sorteo->getEscrutinio())
    $variables['sorteo']['escrutinio'] = array_values($sorteo->getEscrutinio());
  if ($sorteo->getEscrutinioJoker())
    $variables['sorteo']['escrutinio_joker'] = array_values($sorteo->getEscrutinioJoker());
}
