<?php

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function sorteos_theme()
{
  return [
    'sorteos' => [
      'render element' => 'children',
    ],
    'sorteo' => [
      'path' => '/sorteos',
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_commerce_product().
 */
function sorteos_theme_suggestions_sorteo_alter(array &$suggestions, array $variables, $hook)
{
  $original = $variables['theme_hook_original'];
  $sorteo = $variables['elements']['#sorteo'];

  if ($sorteo) {
    $suggestions[] = $original . '__' . $sorteo->bundle();
   
    if (isset($variables['elements']['#view_mode'])) {
      $suggestions[] = 'sorteo__' . $variables['elements']['#view_mode'];
    }
  }

  return $suggestions;
}

/**
 * Prepares variables for sorteo templates.
 *
 * Default template: commerce-product.html.twig.
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing rendered fields.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_sorteo(array &$variables)
{
  /** @var Drupal\sorteos\Entity\SorteoInterface $product */
  $sorteo = $variables['elements']['#sorteo'];

  $variables['sorteo_entity'] = $sorteo;
  $variables['sorteo'] = [];
  foreach (Element::children($variables['elements']) as $key) {

    $variables['sorteo'][$key] = $variables['elements'][$key];
  }
  if ($sorteo->getEscrutinio())
    $variables['sorteo']['escrutinio'] = array_values($sorteo->getEscrutinio());
  if ($sorteo->getEscrutinioJoker())
    $variables['sorteo']['escrutinio_joker'] = array_values($sorteo->getEscrutinioJoker());
  // Ponemos la imagen del decimo 
  if($sorteo->bundle() === 'loteria_nacional') {
    $variables['decimo_cart_url'] = file_create_url($sorteo->field_decimo_imagen->entity->getFileUri());
  }
}



/*
function renombrar_resultados_archivos($form, &$form_state)
{
  if ($form_state->hasValue('resultados')) {
    if ($form_state->getValue('resultados')[0]['fids'] != null) {

      $fid_0 = $form_state->getValue('resultados')[0]['fids'][0];

      $tiposorteo = $form['form_id']['#value'];

      $id_sorteo = $form_state->getValue('id_sorteo')[0]['value'];
      $file_name = ucfirst($tiposorteo) . '-' . $id_sorteo;
      $file_name = trim(preg_replace("/[^0-9A-Za-z]/", '-', $file_name));

      try {
        $file = \Drupal\file\Entity\File::load($fid_0);

        $old_file_name = $file->getFilename();
        $old_file_name = preg_replace('/\\.[^.\\s]{3,4}$/', '', $file->getFilename());

        $new_filename_uri = str_replace($old_file_name, $file_name, $file->getFileUri());
        file_move($file, $new_filename_uri);
        dump($new_filename_uri);
        $file->setFilename($file_name);
        $file->setFileUri($new_filename_uri);
        $file->save();
      } catch (\Exception $e) {
        watchdog_exception('sorteos', $e);
      }
    }
  }
}
*/