<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Render\FormattableMarkup;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\sorteos\Entity\Sorteo;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function veleta_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
  if ($form['#id'] != 'views-exposed-form-comprar-loteria-nacional-page-comprar-loteria') {
    return FALSE;
  }
  $storage = Drupal::getContainer()->get('entity_type.manager')->getStorage('sorteo');
  $nids = $storage->getQuery();

  // Select de sorteos pendientes de celebrar
  $hoy = new \DateTime();
  $nids = $nids->condition('type', 'loteria_nacional')->condition('fecha', $hoy->format('Y-m-d'), '>=')
    ->sort('fecha')
    ->execute();
  if (!$nids) {
    return FALSE;
  }
  $options = [];
  $nodes = $storage->loadMultiple($nids);

  foreach ($nodes as $node) {
    $options[$node->id()] = $node->getName() . ' / ' . $node->getFechaSimple();
  }

  // Start building out our new form element
  $sorteo_field = 'field_sorteo_3_target_id';
  $form[$sorteo_field]['#type'] = 'select';
  $form[$sorteo_field]['#multiple'] = FALSE;

  // Specify the empty option for our select list
  $form[$sorteo_field]['#empty_option'] = '-- Seleccione un Sorteo --';

  // Add the $options from above to our select list
  $form[$sorteo_field]['#options'] = $options;
  unset($form[$sorteo_field]['#size']);
}

function veleta_views_data_alter(array &$data)
{
  $data['sorteo']['sorteos_fecha_hoy'] = array(
    'title' => 'Sorteos Caducados',
    'filter' => array(
      'title' => t('Sorteos Caducados'),
      'help' => t('Sólo muestra los sorteos cuya fecha de celebracion sea mayor que hoy'),
      'field' => 'fecha',
      'id' => 'views_sorteos_caducados'
    ),
  );
}
/**
 * Implements hook_mail().
 */
function veleta_mail($key, &$message, $params)
{
  switch ($key) {
    case 'veleta_log':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = 'Hay un error en loterialaveleta.com';
      $message['body'][] = $params['message'];

      break;
  }
}
/**
 * Implements hook_theme().
 */
function veleta_theme()
{
  return [
    'veleta' => [
      'render element' => 'children',
    ],
    'led' => [
      'variables' => [
        'botes' => [], 'resultados' => [],
      ],
      'render element' => 'children',
    ],
    'botes' => [
      'variables' => [
        'botes' => [],
      ],
    ],
    'resultados' => [
      'variables' => [
        'resultados' => [],
      ],
    ],
    'commerce_order_receipt' => [
      'template' => 'veleta-order-receipt',
      'base hook' => 'commerce_order_receipt',
    ],
  ];
}


function veleta_preprocess_commerce_order_receipt(&$variables)
{
  $order = $variables['order_entity'];
  $newitems = array();
  $count = 0;
  $customer = $order->getCustomer();

  $variables['nombre_completo'] = $customer->get('field_nombre')->value . ' ' . $customer->get('field_apellidos')->value;
  foreach ($order->getItems() as $item => $order_item) {
    $qu = $order_item->get('quantity')->getValue();
    $tp = $order_item->get('total_price')->getValue();
    $newitems[$count]['cantidad'] = $qu[0]['value'];
    $newitems[$count]['precio_total'] = $tp[0]['number'];
    $product_variation = $order_item->getPurchasedEntity();
    $product = $product_variation->getProduct();

    $item = $product->get('field_sorteo_3')->get(0);

    $value = FALSE;
    if (!empty($item)) {
      $value = $item->getValue();
    }
    $sorteoid = $value['target_id'];
    $sorteo = Sorteo::load($sorteoid);
    if ($product->bundle() == 'pena_primitiva') {
      $newitems[$count]['decimo'] = file_create_url($product->field_foto_pena_primitiva->entity->getFileUri());
      $newitems[$count]['numero'] = 'Peña Primitiva';
    }
    if ($product->bundle() == 'decimo_loteria') {
      $numero = $product->get('field_numero_decimo')->get(0);
      $newitems[$count]['decimo'] = file_create_url($sorteo->field_decimo_imagen->entity->getFileUri());
      $numeroarr = $numero->getValue();
      $newitems[$count]['numero'] = $numeroarr['value'];
    }
    $count++;
  }
  $variables['newitems'] = $newitems;
}

/**
 * Implements hook_mail_alter().
 */
function veleta_mail_alter(&$message)
{

  $titulo = 'Loteria La Veleta';

  switch ($message['key']) {

    case 'page_mail':
    case 'page_copy':
    case 'cancel_confirm':
    case 'password_reset':
      $titulo = 'Cambio de Contraseña';
      break;
    case 'register_admin_created':
      $titulo = 'Nueva Cuenta de usuario';
      break;
    case 'register_no_approval_required':
      $titulo = 'Nueva Cuenta de usuario';
      break;
    case 'register_pending_approval':
      $titulo = 'Nueva Cuenta de usuario';
      break;
    case 'register_pending_approval_admin':
      $titulo = 'Nueva Cuenta de usuario';
      break;
    case 'status_activated':
      $titulo = 'Activacion de cuenta';
      break;
    case 'status_blocked':
      $titulo = 'Bloqueo Cuenta de usuario';
      break;
    case 'status_canceled':
  }
  switch ($message['key']) {

    case 'page_mail':
    case 'page_copy':
    case 'cancel_confirm':
    case 'password_reset':
    case 'register_admin_created':
    case 'register_no_approval_required':
    case 'register_pending_approval':
    case 'register_pending_approval_admin':
    case 'status_activated':
    case 'status_blocked':
    case 'status_canceled':
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      foreach ($message['body'] as $key => $body) {
        $html2 = '  <div class="preheader" style="display: none; max-width: 0; max-height: 0; overflow: hidden; font-size: 1px; line-height: 1px; color: #fff; opacity: 0;">
             Accion de usuario en Loteria La Veleta sitio web
             </div>
             <table border="0" cellpadding="0" cellspacing="0" width="100%">

               <tr>
                 <td align="center" bgcolor="#faeede">
                   <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                     <tr>
                       <td align="center" valign="top" style="padding: 26px 24px;">
                         <a href="https://loterialaveleta.com" target="_blank" style="display: inline-block;">
                           <img src="https://loterialaveleta.com/themes/custom/laveletav2/images/logo-loteria-la-veleta-blanco.svg" alt="Logo" border="0" style="display: block; width: 248px;">
                         </a>
                       </td>
                     </tr>
                   </table>
                 </td>
               </tr>
               <tr>
                 <td align="center" bgcolor="#faeede">
                   <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                     <tr>
                       <td align="left" bgcolor="#ffffff" style="padding: 36px 24px 0; font-family: Helvetica, Arial, sans-serif; border-top: 3px solid #d4dadf;">
                         <h1 style="margin: 0; font-size: 32px; font-weight: 700; letter-spacing: -1px; line-height: 48px; color:#222;">' . $titulo . '</h1>
                       </td>
                     </tr>
                   </table>
                 </td>
               </tr>
               <tr>
                 <td align="center" bgcolor="#faeede">
                   <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                     <tr>
                       <td align="left" bgcolor="#ffffff" style="padding: 16px; font-family: Helvetica, Arial, sans-serif; color:#222; font-size: 13px; line-height: 24px; word-break: break-all">
                        ' . strip_tags($body, '<p></p>') . '
                       </td>
                     </tr>

                     <tr>
                       <td align="left" bgcolor="#ffffff" style="color:#222; padding: 24px; font-family:Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px; border-bottom: 3px solid #d4dadf">
                         <p style="margin: 0;">Saludos,<br> El Equipo de La Veleta</p>
                       </td>
                     </tr>

                   </table>
                 </td>
               </tr>
               <tr>
                 <td align="center" bgcolor="#faeede" style="padding: 24px;">
                   <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                     <tr>
                       <td align="center" bgcolor="#faeede" style="padding: 12px 24px; font-family: Helvetica, Arial, sans-serif; font-size: 14px; line-height: 20px; color: #666;">
                         <p style="margin: 0;">Has recibido este email porque has requirido alguna accion de usuario en loterialaveleta.com, puedes borrarlo siempre de forma segura.</p>
                       </td>
                     </tr>
                     <tr>
                       <td align="center" bgcolor="#faeede" style="padding: 12px 24px; font-family:Helvetica, Arial, sans-serif; font-size: 14px; line-height: 20px; color: #666;">
                       <p style="margin: 0;"><a style="font-weight:bold; color:#666; " href="https://loterialaveleta.com">https://loterialaveleta.com</a> Avda. de la Institucion Libre de Enseñanza 1 - 28037 - Madrid</p>
                       </td>
                     </tr>
                   </table>
                 </td>
               </tr>

             </table>';
        $message['body'][$key] = new FormattableMarkup($html2, []);
      }
      break;
  }
}

/**
 * Implements hook_entity_base_field_info_alter().
 */
function veleta_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type)
{
  if ($entity_type->id() == 'commerce_product') {
    // Change the title field label.
    $fields['title']->setLabel(t('Nombre del Producto'));
  }
}


/**
 * Implements hook_toolbar_alter().
 */
function veleta_toolbar_alter(&$items)
{
  $items['administration']['#attached']['library'][] = 'veleta/toolbar';
}

function veleta_menu_local_tasks_alter(&$data, $route_name)
{
  $data["tabs"][0]["entity.user.edit_form"]["#weight"] = -9;
  $data["tabs"][0]["mimonedero.usuario"]["#weight"] = -7; // Mi Monedero
}
